# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='s',
            field=models.SlugField(default='asd', editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
